// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MunicipiosIbge.Api.Infrastructure.Persistence.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MunicipiosIbge.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MunicipalitiesDbContext))]
    [Migration("20260519195015_AllowMunicipalityWithoutMicroregion")]
    partial class AllowMunicipalityWithoutMicroregion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MunicipiosIbge.Api.Domain.Entities.ImmediateRegion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IntermediateRegionId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IntermediateRegionId");

                    b.ToTable("ImmediateRegions", (string)null);
                });

            modelBuilder.Entity("MunicipiosIbge.Api.Domain.Entities.IntermediateRegion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("StateId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("IntermediateRegions", (string)null);
                });

            modelBuilder.Entity("MunicipiosIbge.Api.Domain.Entities.Mesorregion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("StateId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Mesorregions", (string)null);
                });

            modelBuilder.Entity("MunicipiosIbge.Api.Domain.Entities.Microregion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MesorregionId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MesorregionId");

                    b.ToTable("Microregions", (string)null);
                });

            modelBuilder.Entity("MunicipiosIbge.Api.Domain.Entities.Municipality", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ImmediateRegionId")
                        .HasColumnType("integer");

                    b.Property<int?>("MicroregionId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ImmediateRegionId");

                    b.HasIndex("MicroregionId");

                    b.HasIndex("Name");

                    b.ToTable("Municipalities", (string)null);
                });

            modelBuilder.Entity("MunicipiosIbge.Api.Domain.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Acronym")
                        .IsUnique();

                    b.ToTable("Regions", (string)null);
                });

            modelBuilder.Entity("MunicipiosIbge.Api.Domain.Entities.State", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Acronym")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Acronym")
                        .IsUnique();

                    b.HasIndex("RegionId");

                    b.ToTable("States", (string)null);
                });

            modelBuilder.Entity("MunicipiosIbge.Api.Domain.Entities.ImmediateRegion", b =>
                {
                    b.HasOne("MunicipiosIbge.Api.Domain.Entities.IntermediateRegion", "IntermediateRegion")
                        .WithMany("ImmediateRegions")
                        .HasForeignKey("IntermediateRegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IntermediateRegion");
                });

            modelBuilder.Entity("MunicipiosIbge.Api.Domain.Entities.IntermediateRegion", b =>
                {
                    b.HasOne("MunicipiosIbge.Api.Domain.Entities.State", "State")
                        .WithMany("IntermediateRegions")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("MunicipiosIbge.Api.Domain.Entities.Mesorregion", b =>
                {
                    b.HasOne("MunicipiosIbge.Api.Domain.Entities.State", "State")
                        .WithMany("Mesorregions")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("MunicipiosIbge.Api.Domain.Entities.Microregion", b =>
                {
                    b.HasOne("MunicipiosIbge.Api.Domain.Entities.Mesorregion", "Mesorregion")
                        .WithMany("Microregions")
                        .HasForeignKey("MesorregionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mesorregion");
                });

            modelBuilder.Entity("MunicipiosIbge.Api.Domain.Entities.Municipality", b =>
                {
                    b.HasOne("MunicipiosIbge.Api.Domain.Entities.ImmediateRegion", "ImmediateRegion")
                        .WithMany("Municipalities")
                        .HasForeignKey("ImmediateRegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MunicipiosIbge.Api.Domain.Entities.Microregion", "Microregion")
                        .WithMany("Municipalities")
                        .HasForeignKey("MicroregionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ImmediateRegion");

                    b.Navigation("Microregion");
                });

            modelBuilder.Entity("MunicipiosIbge.Api.Domain.Entities.State", b =>
                {
                    b.HasOne("MunicipiosIbge.Api.Domain.Entities.Region", "Region")
                        .WithMany("States")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("MunicipiosIbge.Api.Domain.Entities.ImmediateRegion", b =>
                {
                    b.Navigation("Municipalities");
                });

            modelBuilder.Entity("MunicipiosIbge.Api.Domain.Entities.IntermediateRegion", b =>
                {
                    b.Navigation("ImmediateRegions");
                });

            modelBuilder.Entity("MunicipiosIbge.Api.Domain.Entities.Mesorregion", b =>
                {
                    b.Navigation("Microregions");
                });

            modelBuilder.Entity("MunicipiosIbge.Api.Domain.Entities.Microregion", b =>
                {
                    b.Navigation("Municipalities");
                });

            modelBuilder.Entity("MunicipiosIbge.Api.Domain.Entities.Region", b =>
                {
                    b.Navigation("States");
                });

            modelBuilder.Entity("MunicipiosIbge.Api.Domain.Entities.State", b =>
                {
                    b.Navigation("IntermediateRegions");

                    b.Navigation("Mesorregions");
                });
#pragma warning restore 612, 618
        }
    }
}
